branch-defaults:
  master:
    environment: hastyOgre-dev
global:
  application_name: hastyOgre
  default_ec2_keyname: aws-eb
  default_platform: Node.js
  default_region: us-west-1
  profile: eb-cli
  sc: git
